name: .NET Test Automation
run-name: ${{ github.head_ref || github.ref_name }}-ci-pr

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version:
          - 10.0.x

    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Setup Godot
        uses: solarlabyrinth/action-setup-godot@v3
        with:
          version: 4.7-stable
          csharp: true
          name: godot
          export-templates: true

      - name: Setup GODOT_BIN
        run: echo "GODOT_BIN=$(which godot)" >> $GITHUB_ENV

      - name: Restore dependencies
        run: dotnet restore ./src/${{ github.event.repository.name }}.slnx

      - name: Build
        run: dotnet build --no-restore ./src/${{ github.event.repository.name }}.slnx

      - name: Test
        run: dotnet test --no-build --settings ./src/runsettings --verbosity normal ./src/${{ github.event.repository.name }}.slnx